### ISSUE TITLE
Build files are commited

### ISSUE THREAD

**Issue by ThatOSDeveloper** [markhan101/IrfanOS#2]
Please look into a .gitignore file here is the basic idea just put files or filetypes in it you would do *.filetype or filename to stop it from being pushed

**Comment by markhan101** [comment]
Hi, 😊, yes i have been meaning to do this. I got caught up in another project from my college so didn't really pay attention. I'll do it as soon as possible. Thank you.

**Comment by ThatOSDeveloper** [comment]
I can make a quick PR for this fix

**Comment by markhan101** [comment]
Hi, Thank you very much, I didn't read it sooner or else I would have responded. I really appreciate it 😊.
